# -*- coding: utf-8 -*-
"""scrap my boy

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1G9wTVJ8LAuhPUTd3A651-XPp_s3sK3MF
"""

import json
import requests
from pprint import pprint
# SCELE_URL = 'https://scele.cs.ui.ac.id'

# !pip install selenium
# !apt-get update
# !apt install chromium-chromedriver

from selenium import webdriver
from selenium.common.exceptions import NoSuchElementException
import os

import sys
sys.path.insert(0,'/usr/lib/chromium-browser/chromedriver')
from time import time
start = time()
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')
wd = webdriver.Chrome('chromedriver',chrome_options=chrome_options)

with open('env.json', 'r') as f:
    datastore = json.load(f)

a = wd.get("http://scele.cs.ui.ac.id")
username_input = wd.find_element_by_name('username')
username_input.send_keys(datastore['username'])

password_input = wd.find_element_by_name('password')
password_input.send_keys(datastore['password'])

login_form = wd.find_element_by_class_name('navbar-form')
login_form.submit()

for course in datastore['courses']:
  wd.get(course)
  print(wd.find_element_by_class_name('page-header-headings').text)
  all_spans = wd.find_elements_by_xpath("//span[@class='unread']")
  
  for ass in all_spans :
#   print(ass.text)
    parent = ass.find_element_by_xpath('..')
    print(parent.text)
  if(len(all_spans) == 0):
    print('no unread posts!')
#   print('aa')
print('completed in %.2f' % (time() - start))

